### PR TITLE
Debugging Animas missing records 

### PR DESCRIPTION
**Pull request by gniezen**
When there is a missing record, we should print out the record before and just after the missing record so we have a better indication of where it went missing.

See https://trello.com/c/skctayOf for details.

### CODE REVIEW

**Comment by gniezen** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;skctayOf&#x2F;21-uploader-bug-animas-upload-fails-due-to-missing-records"> [uploader][bug] Animas upload fails due to missing records</a>

**Comment by gniezen** [comment]
@jebeck I'm pinging you for code review as I remember you running into the "missing record" issue once. This PR should make it a bit easier to debug in future. (This was prompted by the user report that we couldn't investigate further as there were issues with the pump).

**Comment by jebeck** [comment]
LGTM 👍

**Comment by gniezen** [comment]
Merging, but not building a new release as this is a minor change and not user-facing

**Pull request merged**
