### PR TITLE
Adding time difference checks to device drivers

### PR DESCRIPTION
**Pull request by gniezen**
This PR contains all the changes to the device drivers for checking the difference between device time and server time. The UI will be a separate PR.

### CODE REVIEW

**Comment by gniezen** [comment]
[#477 ⁃ [uploader] [timezones] as a user, i want the uploader to warn me of any difference between my device time and computer time or selected timezone in the Uploader and my computer timezone](https://trello.com/c/1eAw2Fpc/175-477-uploader-timezones-as-a-user-i-want-the-uploader-to-warn-me-of-any-difference-between-my-device-time-and-computer-time-or-se)

**Comment by gniezen** [comment]
Still needs a new platform-client version.

**Comment by pazaan** [comment]
@gniezen Looks good :)

**Comment by pazaan** [comment]
Commits since last review look good to me 👍

**Pull request merged**
