### PR TITLE
Block mode auto upload

### PR DESCRIPTION
**Pull request by gniezen**
Removing Upload button for block mode devices and uploading immediately after file is chosen

### CODE REVIEW

**Comment by gniezen** [comment]
@jebeck While attempting to fix an error being thrown if you press the Upload button before the file has finished loading from OmniPod, it occurred to me that it may just be easier to remove the Upload button. If this is the route we want to go, this PR needs to be reviewed and merged before we can push OmniPod changes to prod.

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gpqk1XL0&#x2F;23-uploader-fix-error-when-clicking-upload-on-omnipod-after-filename-displayed-but-before-browser-has-finished-reading-file"> [uploader] fix error when clicking Upload on OmniPod after filename displayed but before browser has finished reading file</a>

**Comment by gniezen** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gpqk1XL0&#x2F;23-uploader-fix-error-when-clicking-upload-on-omnipod-after-filename-displayed-but-before-browser-has-finished-reading-file"> [uploader] fix error when clicking Upload on OmniPod after filename displayed but before browser has finished reading file</a>

**Comment by jebeck** [comment]
Please remove the `clearBlockModeFile` function since it's no longer being used.

**Comment by jebeck** [comment]
LGTM, just please remove the unused function as mentioned above. The lack of a callback being provided to `appActions.upload` does not look like an issue to me. I `git grep`ed for the usage, had to follow it down through the components a bit, but basically it doesn't look to me as if we are ever providing that callback, so should be fine. (And I'll think about changing that in the redux migration.)

**Comment by gniezen** [comment]
@jebeck Discovered that showing ellipsis for long filenames was not working anymore, so made some changes to the CSS after your review. I'm going to merge so long in order to build a new version for testing, but it'll be good if you can just double-check commit 5060f7e.

**Pull request merged**
