### PR TITLE
final Tandem bugfixes

### PR DESCRIPTION
**Pull request by jebeck**
Replaces #190 (wrong merge target).

There will be two bugfixes on this PR, but it's a WIP right now, **don't merge**

- [x] handle previously unhandled basal rate change type combos
- [x] handle interrupted quick bolus (due to occlusion, but I don't think that's relevant, just happens to be how I caught it)

### CODE REVIEW

**Comment by jebeck** [comment]
Ready for review now. Ping @gniezen

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GVVdQ8Ic&#x2F;24-uploader-device-final-bugfixes-for-initial-tandem-prod-release"> [uploader] [device] final bugfixes for initial Tandem prod release</a>

**Comment by gniezen** [comment]
Turns it we still didn't catch them all, and the "unhandled changetype" error wasn't being thrown. I caught this because I was checking the issue I mentioned were a temp basal starts at the same time  that you're scheduling a new segment - we were missing `timed_segment|temp_rate_start`. 

I've added `timed_segment|temp_rate_start` and fixed the error not being thrown correctly. The rest LGTM and I'll merge. @jebeck to just double-check my changes.

**Comment by jebeck** [comment]
Your additional changes look great @gniezen Good catches!

**Pull request merged**
