### PR TITLE
Kjq/update asante

### PR DESCRIPTION
**Pull request by kentquirk**
This enables the Asante SNAP (not the MySnap) pump and makes it so it works with the current version of the uploader.

This is an intermediate state because proper Asante MySnap support is going to require a bit of rework.

### CODE REVIEW

**Comment by kentquirk** [comment]
@jebeck -- this is now ready for the next step -- creation of a simulator. Right now, it's back to the state where the driver works as well as it did before, except that now it also can work with both old and new Asante pumps using the Asante XML files to generate some of the code.

**Comment by jebeck** [comment]
Hey @kentquirk first thing tomorrow I'm going to try to update this with the changes that have come in on master. OK by you? You don't have anything unpushed?

**Comment by kentquirk** [comment]
I am merging it now. Will push after testing.

**Comment by kentquirk** [comment]
@jebeck -- merged from master.

**Comment by jebeck** [comment]
This works for me locally, so as discussed with @kentquirk I'm merging. My work on the Asante simulator will be on a fresh branch.

**Pull request merged**
