### PR TITLE
Displays filename in UI before loading file

### PR DESCRIPTION
**Pull request by gniezen**
This shortens the delay between selecting the .ibf file and seeing it in the Uploader UI.

### CODE REVIEW

**Comment by gniezen** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hgy0uNpI&#x2F;10-0-ux-2-dev-1-tst-uploader-omnipod-bundle-of-small-tasks"> &lt;0:ux, 2:dev, 1:tst&gt; [uploader] OmniPod bundle of small tasks</a>

**Comment by gniezen** [comment]
Ping @jebeck for review.

**Comment by jebeck** [comment]
Maybe remove the setting of the filename *again* in line 567, inside `reader.onloadend`? Unnecessary now.

Otherwise LGTM, and verified that it improves speed from my OmniPod from 6.9s to negligible. :)

**Comment by gniezen** [comment]
Great! OK, not setting filename twice anymore. Merging.

**Pull request merged**
