### PR TITLE
Modify device screen copy

### PR DESCRIPTION
**Pull request by pazaan**

### CODE REVIEW

**Comment by pazaan** [comment]
[<S> [uploader] Medtronic 6 - Driver copy for Choose Devices screen](https://trello.com/c/BF1URAvH/95-s-uploader-medtronic-6-driver-copy-for-choose-devices-screen)

**Comment by gniezen** [comment]
@pazaan Hmm, why did we never merge this one?

**Comment by pazaan** [comment]
It's being merged into 600-series, but the QA doc has a few other error message enhancements attached to it.

**Comment by pazaan** [comment]
Deleted, because there were too many conflicts at this stage, and I cherry picked the changes into `pazaan/electron-medtronic600`

**Pull request closed without merging**
