### PR TITLE
ability to download dataservices POST records (in device debug mode)

### PR DESCRIPTION
**Pull request by jebeck**
Not sure this is the most elegant way to do this @gniezen but it's working for me presently. Thoughts?

### CODE REVIEW

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QlPtpq3Y&#x2F;30-uploader-add-download-link-for-dataservices-post-records-and-mock-server-for-dataservices-api"> [uploader] add download link for &quot;dataservices&quot; POST records and mock server for dataservices API</a>

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QlPtpq3Y&#x2F;30-uploader-add-download-link-for-dataservices-post-records-and-mock-server-for-dataservices-api"> [uploader] add download link for &quot;dataservices&quot; POST records and mock server for dataservices API</a>

**Comment by jebeck** [comment]
Obviously don't merge this yet @gniezen Not sure why I broke tests 😕

**Comment by gniezen** [comment]
OK, tests are passing now, I've made minor changes to the formatting of the download links, and made some updates after merging latest changes from #251 . The only thing that still bugs me is having `mock-dataservices` in main directory, but I'm not sure where to move it - maybe `scripts/` or `config/`?

**Comment by jebeck** [comment]
Well `mock-dataservices` is never going to come into master, right? If we have to wait to merge #251 then we can just delete it prior to merge. If it bothers you for that short of time, move it wherever you want, I'm not picky 😜

**Pull request merged**
