### PR TITLE
upgrade react-select

### PR DESCRIPTION
**Pull request by krystophv**

### CODE REVIEW

**Comment by jebeck** [comment]
:+1: but I'll not merge yet until know @gniezen is OK with sequencing I proposed in a comment on #260.

**Comment by krystophv** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qX7TgmqM&#x2F;8-ux-1-dev-5-tst-0-uploader-in-clinic-add-new-screens-for-in-clinic-account-creation-styles-only"> &lt;ux:1 dev:5 tst:0&gt; [uploader] [in-clinic] add new screens for in-clinic account creation, styles only</a>

**Comment by gniezen** [comment]
Merging.

**Comment by gniezen** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;o9yH83Bk&#x2F;2-ux-0-dev-2-tst-1-uploader-device-onetouch-verioiq"> &lt;ux:0, dev:2, tst:1&gt; [uploader] [device] OneTouch VerioIQ</a>

**Pull request merged**
