### PR TITLE
Release 2.10.0

### PR DESCRIPTION
**Pull request by gniezen**
This release is a bulk update of all the dependencies that require no or minimal code changes, including moving to Electron v4. See attached card for details.

### CODE REVIEW

**Comment by gniezen** [comment]
[Update dependencies (including Electron)](https://trello.com/c/2DYR2Xlx/517-update-dependencies-including-electron)

**Comment by gniezen** [comment]
Currently awaiting testing. I have to create a PR _before_ we start testing, otherwise the binary that we tested with gets overwritten.

**Comment by gniezen** [comment]
QA passed, ready for prod. Going to tag and push to prod from release branch, then merge this when PR is approved.

**Comment by pazaan** [comment]
@gniezen - do we want to close this out until we have a way to make Electron 4 work with the 600-series driver?

**Comment by gniezen** [comment]
I think the least disruptive way forward is to downgrade to Electron v3 as a hotfix in this release, then re-test all supported devices on both macOS and Windows.

**Comment by gniezen** [comment]
@krystophv Just need a PR approval for the version bump to v2.10.1.

**Pull request merged**
