### PR TITLE
wire in simulator and move basal processing there

### PR DESCRIPTION
**Pull request by jebeck**
**WIP** Don't merge!

Working branch for what it says on the tin.

### CODE REVIEW

**Comment by jebeck** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0OZr6y4F&#x2F;18-3-tandem-simulate-basals-including-all-change-types-i-e-include-suspended-and-resumed-change-types"> &lt;3&gt; [tandem] simulate basals, including all change types (i.e., include suspended and resumed change types)</a>

**Comment by gniezen** [comment]
Two issues I've seen while reviewing with my data:

- My first scheduled basal is missing
- If a scheduled basal is running for a couple of days, it suddenly disappears while scrolling through the daily view in Blip the day before the basal is suspended. Error is something like:
screen shot 2015-10-28 at 10 38 41
I just want to make sure this is not a known issue before I look further?

**Comment by jebeck** [comment]
Disregard those errors in tideline/blip @gniezen The situation you describe is a client-side bug. The errors themselves are (probably) unrelated (but also harmless) SVG errors that happen because of rounding weirdness in D3 and SVG rendering.

This is an example where looking at the raw data (e.g., through the `window.tidelineData` object in the console) is often a much better mechanism for verifying one's work.

**Comment by gniezen** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aTKjNKVC&#x2F;19-1-tandem-decide-on-and-implement-strategy-for-computing-duration-of-final-basal"> &lt;1&gt; [tandem] decide on and implement strategy for computing duration of final basal</a>

**Pull request merged**
