### PR TITLE
Animas mmol/L support

### PR DESCRIPTION
**Pull request by gniezen**
See https://trello.com/c/Ry3Cz0eC.

### CODE REVIEW

**Comment by gniezen** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ry3Cz0eC&#x2F;18-uploader-bug-animas-mmol-l-support"> [uploader][bug] Animas mmol&#x2F;L support</a>

**Comment by gniezen** [comment]
@darinkrauss - can you do the code review for this small PR? I'm pinging you as you're probably the most familiar with the issue.

**Comment by gniezen** [comment]
Note that so far three of the four users that reported this issue have reported successful uploads using this on alpha.

**Comment by darinkrauss** [comment]
:shipit:

**Pull request merged**
