### PR TITLE
Bug fix: Abbott FreeStyle meters with a large number of records

### PR DESCRIPTION
**Pull request by gniezen**
For more details: https://trello.com/c/WpikEtp1

### CODE REVIEW

**Comment by gniezen** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WpikEtp1&#x2F;20-uploader-bug-abbott-devices-with-large-number-of-records-fail-to-upload"> [uploader][bug] Abbott devices with large number of records fail to upload</a>

**Comment by gniezen** [comment]
Pinging @jebeck for review?

**Comment by jebeck** [comment]
So the probing and the `getSerialNumber` were the two extraneous reads?

LGTM.

**Comment by gniezen** [comment]
@jebeck Yep, there's basically just one command you can send to this device (`mem`) and it returns all data, including serial number. (This is different from the PXtra, where you have two different commands). If 400 records take 20s to download, sending the same command three times (probing, get serial number, get data) would take 3 x 20s = 60s.

**Pull request merged**
