### PR TITLE
Add `bg/out-of-range` annotations to `cbg` types.

### PR DESCRIPTION
**Pull request by pazaan**
@gniezen

### CODE REVIEW

**Comment by pazaan** [comment]
While starting to implement the annotations for SMBG, I realised that it doesn't make much sense to do so. The Bolus Wizard only lets you enter a number in the range of the Contour Next Link (20mg/dL to 600mg/dL). You would want both 20 and 600 to show up as valid SMBG numbers (not "Hi" or "Lo"). If you have a reading outside of this range, it's not automatically transmitted to the pump, and you couldn't enter it into the Bolus Wizard, because you wouldn't know what the number is.
Thoughts?

**Comment by gniezen** [comment]
I vaguely remember coming to the same conclusion while working on SMBG records - that there isn't really a way to get out-of-range numbers, for the reasons you specified. Will you mention something to that effect in the checklist?

**Comment by pazaan** [comment]
@gniezen Can you just re-review? I removed a duplicate const, just want to make sure you're happy with that.

**Comment by gniezen** [comment]
LGTM! I'll merge it in so that I can start a new branch for the CGM timestamp fixes.

**Comment by gniezen** [comment]
[<L> Medtronic Alpha Test - Issue Resolution Card [uploader]](https://trello.com/c/oY4TZF73/28-l-medtronic-alpha-test-issue-resolution-card-uploader)

**Pull request merged**
