### PR TITLE
Add new insulin settings for 600-series

### PR DESCRIPTION
**Pull request by pazaan**
* Fixes https://trello.com/c/7hyUrl24

### CODE REVIEW

**Comment by pazaan** [comment]
@gniezen - it's only just occurred to me. Would it make more sense to close this PR, and open a PR against your `add-pump-settings` branch instead?

**Comment by pazaan** [comment]
[Additional pump settings](https://trello.com/c/7hyUrl24/415-additional-pump-settings)

**Comment by gniezen** [comment]
In terms of being able to test everything together it will probably make more sense to branch of my PR, yes :+1:

**Comment by pazaan** [comment]
Closing this PR, and re-opening a new PR against `add-pump-settings`

**Comment by pazaan** [comment]
Closed in favour of https://github.com/tidepool-org/chrome-uploader/pull/698

**Pull request closed without merging**
