### PR TITLE
updates to uploader's redux approach to match blip

### PR DESCRIPTION
**Pull request by jebeck**
WIP Do not merge!

This is a placeholder for updates to the uploader's redux implementation for compatibility with blip's. It may hang out for a while, that's on me to keep it up to date, etc.

### CODE REVIEW

**Comment by jebeck** [comment]
OK, what's here is the easiest changes to make to at least have the (directory) _structure_ of the redux implementations across blip and the uploader as similar as possible. @krystophv can you review? I think bringing in this, #261 and #262 plus perhaps #157 would make a good next bundle of changes on master to test (the first three PRs just need "didn't break anything" testing, so adding the VerioIQ to have something substantial to test feels like it helps flesh out the bundle, IMO).

CC @gniezen

**Comment by gniezen** [comment]
@jebeck @krystophv Sounds like a good strategy to me. What still needs to be done before we merge and build:

- This PR still needs to be reviewed and approved by @krystophv 
- #262 still needs some work from @krystophv and approval by @jebeck 
- I still need to check HI/LO on #157

**Comment by krystophv** [comment]
@jebeck @gniezen This LGTM

**Comment by gniezen** [comment]
@krystophv Can you resolve conflicts for this branch and #261, then we can start merging them (together with #157) to build a new RC?

**Comment by krystophv** [comment]
Yeah I should be able to get master merged down into them today.

**Comment by gniezen** [comment]
Merging.

**Comment by gniezen** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;o9yH83Bk&#x2F;2-ux-0-dev-2-tst-1-uploader-device-onetouch-verioiq"> &lt;ux:0, dev:2, tst:1&gt; [uploader] [device] OneTouch VerioIQ</a>

**Pull request merged**
