### PR TITLE
jellyfish errors fix

### PR DESCRIPTION
**Pull request by jh-bate**
@darinkrauss this uses the update to the platform-client from PR https://github.com/tidepool-org/platform-client/pull/59

### CODE REVIEW

**Comment by darinkrauss** [comment]
We'll obviously need to do an official, versioned release of platform-client before we merge into master here, though. LGTM, otherwise.

**Comment by jh-bate** [comment]
@jebeck made those changes as discussed - ready for you to check

**Comment by jebeck** [comment]
OK, LGTM, just remember to publish new platform-client first and update here. Also you should coordinate with @gniezen re: merge sequence.

**Comment by jh-bate** [comment]
This PR will be integrated by @gniezen with his other changes for testing

**Pull request merged**
