### PR TITLE
Release 2.16.0

### PR DESCRIPTION
**Pull request by gniezen**
Please verify that attached Trello cards are the only features merged into this release.

### CODE REVIEW

**Comment by gniezen** [comment]
[Update code signing certificates](https://trello.com/c/Uv8NwRg4/600-update-code-signing-certificates)

**Comment by pazaan** [comment]
@gniezen You asked me to check that this review only contains changes for code signing, but it looks like it contains driver updates for Windows 10 as well...

**Comment by gniezen** [comment]
The new code signing process for Windows 10, where it has to be submitted to the Microsoft hardware dashboard, necessitated a number of changes to the drivers to make it work. It's all the changes in https://github.com/tidepool-org/chrome-uploader/pull/867.

**Comment by gniezen** [comment]
Forgot to bump version number, oops!

**Pull request merged**
