### PR TITLE
Support guardian connect

### PR DESCRIPTION
**Pull request by Slumber86**
Added new device for carelink, format is nearly the same of minimed,
only  manual readings have  “BGCapturedOnPump” event with no action
associated

_My girlfirend has this device and this work is derived from a quick hack I did to allow her to upload her data to tidepool, that is the only place where she can also upload omipod data_

### CODE REVIEW

**Comment by pazaan** [comment]
@Slumber86, so that we are able to test, are you able to share with us a CSV file of Guardian Connect data? If so, you can find me on Tidepool's public Gitter channel (https://gitter.im/tidepool-org/public). Please find me a DM me so that we can share contact details.

Thanks!

**Comment by gniezen** [comment]
Hi @Slumber86 ! We don't have access to a Guardian Connect ourselves, but if you can send a CareLink CSV file with Guardian Connect data to gerrit@tidepool.org I can use that to test the code and get it merged. Please let me know if this is possible.

**Comment by Slumber86** [comment]
Yes, sorry for late response, i have some european CSVs that I managed to load changing only the date format. I attach them to this PR

[Archivio.zip](https://github.com/tidepool-org/chrome-uploader/files/1337715/Archivio.zip)

**Comment by gniezen** [comment]
I've tried uploading the CareLink CSV after changing the date format from DD-MM-YYYY to MM-DD-YYYY, but I'm still getting an error:

```
DriverManager    | DriverManager set up in normal mode: all errors will surface in UI only.
CareLinkDriver   | Carelink Setup!
CareLinkDriver   | Carelink Connect!
CareLinkDriver   | Carelink GetConfigInfo!
CareLinkDriver   | Carelink FetchData!
CareLinkDriver   | Carelink data 634641
CareLinkDriver   | Find and remove overlapping uploads from the same device model
CareLinkDriver   | Separate into per-device arrays
CareLinkDriver   | Most recent timestamp for device Guardian Connect: 2017-07-26T14:00:00
CareLinkDriver   | Guardian Connect has 8 time changes
CareLinkDriver   | Most recent timestamp for device Guardian Connect : CGM: 2017-07-26T06:59:00
CareLinkDriver   | Guardian Connect : CGM has 0 time changes
CareLinkDriver   | Carelink Cleanup!
CareLink CLI: Error processing CareLink data: { Error: Can't bootstrap to UTC! Pump and CGM time changes do not match!
```

I think the issue is that when the driver detects CGM data, it expects there to be pump data as well. Of course with a Guardian Connect there is only CGM data and thus only one set of time changes.

@Slumber86  This doesn't explain how you could upload successfully. Did you make any other changes to the CSV before uploading?

**Comment by gniezen** [comment]
@Slumber86 I have managed to get the first csv to upload correctly after changing the delimiter from `;` to `,` as it has no time changes. So as you said, the second CSV is failing due to time changes. 

Note that we will probably be deprecating the CareLink driver at the end of the year, as we now support direct uploads through our Medtronic (Direct) driver. This may change how much time you want to spend fixing this issue?

**Comment by Slumber86** [comment]
Do you know if he medtronic direct will support guardian connect? if so I can work on supporting this way of upload.

**Comment by gniezen** [comment]
To be honest I have no idea - it's worth a shot. Do you have a Bayer Contour Next Link to upload it with? (We do not support the CareLink stick for direct upload)

**Comment by Slumber86** [comment]
No, actually she has guardianConnect + iOS app.
Manual readings are uploaded to tidepool from mylife omipod (she still has to insert them manually, because the version with integrated glucometer is not approved in Italy)

**Comment by gniezen** [comment]
[#480 ⁃ [uploader] Merge Guardian support PR into CareLink driver](https://trello.com/c/BnduZswI/216-480-uploader-merge-guardian-support-pr-into-carelink-driver)

**Comment by gniezen** [comment]
Medtronic has disabled the ability to download CSV files from CareLink for both US and EU servers, which makes this PR unfeasible going forward.

**Pull request closed without merging**
